language: node_js
sudo: false
node_js:
  - '5.4.1'
cache:
  directories:
    - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install
  - gulp
